### ISSUE TITLE
这个编译的时候opencv报错，能请教一下楼主么

### ISSUE THREAD

**Issue by wangpoet** [iamhankai/vehicle-retrieval-kCNNs#1]

**Comment by iamhankai** [comment]
What's the error? And what version is your opencv?

**Comment by Zhouhenry** [comment]
I had feced the error was opencv too;my error is: openCV Error: Unspecified error(Could not open the file storage.Check the path and permissions) in cvSave, file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\core\src\persistence.cpp, line 5036.

And my opencv version is 2.4.9, and i had also tried 2.4.10, but also failed .Can i e-mail with you?

**Comment by wangpoet** [comment]
Error: Unspecified error(Could not open the file storage.Check the path and permissions) in cvSave, file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\core\src\persistence.cpp, line 5053

Version 2.4.10

Thanks for your time

**Comment by iamhankai** [comment]
We used opencv2.4.10 in our implementation. Please compile the project with Release mode.

**Comment by Zhouhenry** [comment]
I had compiled the project with Release mode, but also failed. And I have tried another two computers, also failed. can you give me your compiled project(the total caffe folder).Thanks for your time.

**Comment by iamhankai** [comment]
链接: http://pan.baidu.com/s/1slPjbGh 密码: tabf

**Comment by Zhouhenry** [comment]
Thanks for your help， I will try it.

**Comment by iamhankai** [comment]
Please use this version of caffe: https://github.com/BVLC/caffe/tree/714d0acad8c66d64ddf7b83b9a239f7efc017894

**Comment by auvx** [comment]
我也遇到了同样的问题，请问楼主是怎么解决的？
